-- ============================================================
-- Nexorix - Bancos en vivo + antifraude + opt-in de WhatsApp
-- PostgreSQL 14+ (probado en 16). Es IDEMPOTENTE: se puede ejecutar varias veces.
--
-- Requisito: las tablas base (users, accounts, financial_transactions...) ya existen.
-- Se crean arrancando el backend UNA vez con spring.jpa.hibernate.ddl-auto=update
-- (es el valor por defecto de application.properties). Este script solo agrega lo nuevo
-- con los MISMOS nombres que usa Hibernate, mas indices y restricciones extra.
--
--   psql -U postgres -d nexorix -f db/01-bank-fraud-schema.sql
-- ============================================================

BEGIN;

-- 1) Perfil del usuario: opt-in de WhatsApp y celular de seguridad (alertas criticas).
ALTER TABLE users ADD COLUMN IF NOT EXISTS whatsapp_notifications_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS security_phone varchar(20);

-- 2) Cuentas de Nexorix <-> cuentas del banco (la referencia la da el agregador).
CREATE TABLE IF NOT EXISTS bank_links (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint       NOT NULL REFERENCES users(id),
    account_id   bigint       NOT NULL UNIQUE REFERENCES accounts(id),
    bank         varchar(40)  NOT NULL,
    external_ref varchar(100) NOT NULL UNIQUE,
    created_at   timestamp(6) NOT NULL DEFAULT now()
);

-- 3) Cada webhook recibido. event_id UNICO = idempotencia (el banco puede reintentar).
CREATE TABLE IF NOT EXISTS bank_events (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         varchar(100) NOT NULL UNIQUE,
    user_id          bigint       NOT NULL REFERENCES users(id),
    account_id       bigint       NOT NULL REFERENCES accounts(id),
    bank             varchar(40)  NOT NULL,
    kind             varchar(30)  NOT NULL
        CHECK (kind IN ('EXPENSE','INTERNAL_TRANSFER','THIRD_PARTY_TRANSFER','INCOME')),
    direction        varchar(6)   NOT NULL CHECK (direction IN ('DEBIT','CREDIT')),
    amount           numeric(19,2) NOT NULL CHECK (amount > 0),
    label            varchar(150) NOT NULL,
    counterparty_ref varchar(100),
    city             varchar(80),
    country          varchar(2),
    latitude         double precision,
    longitude        double precision,
    ip               varchar(45),
    occurred_at      timestamp(6) NOT NULL,
    status           varchar(10)  NOT NULL CHECK (status IN ('APPLIED','BLOCKED','RELEASED')),
    risk_level       varchar(10)  NOT NULL DEFAULT 'NONE',
    risk_reason      varchar(300),
    transaction_id   bigint,
    created_at       timestamp(6) NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bank_events_user ON bank_events (user_id, occurred_at);

-- 4) UserBehaviorLog: comercios / categorias habituales, destinatarios frecuentes y lugares comunes.
CREATE TABLE IF NOT EXISTS user_behavior_log (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint       NOT NULL REFERENCES users(id),
    event_type     varchar(20)  NOT NULL CHECK (event_type IN ('PURCHASE','TRANSFER')),
    merchant_key   varchar(100),
    merchant_name  varchar(150),
    category       varchar(40),
    recipient_key  varchar(100),
    recipient_name varchar(150),
    amount         numeric(19,2),
    country        varchar(2),
    city           varchar(80),
    latitude       double precision,
    longitude      double precision,
    ip             varchar(45),
    occurred_at    timestamp(6) NOT NULL,
    created_at     timestamp(6) NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_behavior_user_time      ON user_behavior_log (user_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_behavior_user_merchant  ON user_behavior_log (user_id, merchant_key);
CREATE INDEX IF NOT EXISTS idx_behavior_user_recipient ON user_behavior_log (user_id, recipient_key);

-- 5) Avisos dentro de la app (anomalias leves) y registro de alertas criticas.
CREATE TABLE IF NOT EXISTS app_notifications (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint       NOT NULL REFERENCES users(id),
    severity      varchar(10)  NOT NULL CHECK (severity IN ('INFO','WARNING','CRITICAL')),
    title         varchar(120) NOT NULL,
    body          varchar(500) NOT NULL,
    channels      varchar(80)  NOT NULL DEFAULT 'APP',
    bank_event_id bigint,
    is_read       boolean      NOT NULL DEFAULT false,
    created_at    timestamp(6) NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notif_user_time ON app_notifications (user_id, created_at);

COMMIT;

-- ------------------------------------------------------------
-- OPCIONAL: extensiones geograficas. Nexorix calcula la distancia (haversine) en Java,
-- asi que NO son necesarias para que la app funcione. Solo si quieres consultar la
-- distancia desde SQL (auditoria, reportes) para el antifraude:
--
--   CREATE EXTENSION IF NOT EXISTS cube;
--   CREATE EXTENSION IF NOT EXISTS earthdistance;   -- requiere cube; es contrib de PostgreSQL
--   SELECT earth_distance(ll_to_earth(4.711,-74.0721), ll_to_earth(25.7617,-80.1918)) / 1000 AS km;
-- ------------------------------------------------------------
